[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'bogado/file-line'

[[plugins]]
repo = 'jiangmiao/auto-pairs'
hook_add = '''
    " Disable default <BS> mapping because it maps <C-h>, which is used elsewhere
    " The original <BS> behavior is mapped with AutoPairsDelete() down below
    let g:AutoPairsMapBS = 0
    " Disable jumping multiline close
    let g:AutoPairsMultilineClose = 0
'''

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'kana/vim-textobj-lastpat'

[[plugins]]
repo = 'Julian/vim-textobj-variable-segment'

[[plugins]]
repo = 'Konfekt/FastFold'

[[plugins]]
repo = 'tpope/vim-eunuch'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'tpope/vim-surround'
hook_add = '''
    xmap ( S)
    xmap { S{
    xmap [ S]
    xmap " S"
    xmap ' S'
    xmap ` S`
    xmap T St
'''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-vinegar'
depends = ['nerdtree']

[[plugins]]
repo = 'othree/html5.vim'

[[plugins]]
repo = 'gregsexton/MatchTag'

[[plugins]]
repo = 'posva/vim-vue'

[[plugins]]
repo = 'tpope/vim-liquid'

[[plugins]]
repo = 'ap/vim-css-color'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'

[[plugins]]
repo = 'othree/csscomplete.vim'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'uarun/vim-protobuf'

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'othree/yajs.vim'

[[plugins]]
repo = 'othree/es.next.syntax.vim'

[[plugins]]
repo = 'kchmck/vim-coffee-script'

[[plugins]]
repo = 'gabrielelana/vim-markdown'
hook_add = '''
    let g:markdown_enable_mappings = 0
'''

[[plugins]]
repo = 'tpope/vim-git'

[[plugins]]
repo = 'morhetz/gruvbox'

[[plugins]]
repo = 'rakr/vim-one'

[[plugins]]
repo = 'rakr/vim-two-firewatch'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
depends = ['vim-airline']

[[plugins]]
repo = 'vim-scripts/matchit.zip'

[[plugins]]
repo = 'zhuochun/vim-snippets'
